
[cursor.style]
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Normal"

[font.offset]
x = 0
y = 0

[selection]
save_to_clipboard = true

[window]
opacity = 0.65

[window.padding]
x = 30
y = 30

[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]
